#@ load("@ytt:data", "data")
---
apiVersion: v1
kind: Secret
metadata:
  name: provider-ca-cert
type: service.binding/ca-certificates
stringData:
  type: ca-certificates
  ca.crt: #@ data.values.provider.ca_cert
